var semangat = "Semangat...";
console.log("TUGAS 1:");
console.log(semangat.repeat(5));
console.log("=======================================");
var bintang = "*";
console.log("TUGAS 2");
console.log(bintang.repeat(5));
console.log(bintang.repeat(20));
console.log(bintang.repeat(40));
console.log(bintang.repeat(60));
console.log(bintang.repeat(100));
console.log(bintang.repeat(60));
console.log(bintang.repeat(40));
console.log(bintang.repeat(20));
console.log(bintang.repeat(5));
